Algoritmo "ex02"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/08/2026
Var
// Seção de Declarações das variáveis 
nome: caractere


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("digite seu nome: ")
leia(nome)
escreval("Olá, ", nome, "! Bem-vindo ao Iteam")

Fimalgoritmo