Algoritmo "EX03"

// Professor: Helida Batista
// Autor(a): Abel Benício
// Data: 04/08/2026

Var
  // Seção de Declarações das variáveis
  // número
  num : inteiro
  // número 2
	num2 : inteiro
	// media
  med : inteiro
Inicio
// Seção de Comandos
//lendo o primeiro numero
escreval("Digite um número: ")
leia(num)
//lendo o segundo numero
escreval("Digite um número: ")
leia(num2)

// media aritimetica dos dois numeros
med <- (num + num2)/2

escreval("Sua média aritimética é ", med)








fimalgoritmo