Algoritmo "semnome"

// Data atual  : 07/08/2026
Var
   // Seção de Declarações das variáveis
   num : vetor[0..7] de real // vetor que vai ser usado
   i : inteiro // variavel generica pro laço de repitiçao
   soma : real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   soma <- 0 // vai fazer para o encaixe dos valores em suas posiçoes nos vetores

   //leitura dos numeros
   para i de 0 ate 7 faca

      escreval("digite um numero", i + 1, ": ")
      leia(num[i])


   fimpara


Fimalgoritmo