Algoritmo "EX05"
// # Exercício 05 — Salário Mensal
// Professor: Helida Batista
// Autor(a): Abel Benício
// Data: 04/08/2026

Var
  // Seção de Declarações das variáveis
  // base do triangulo
  base : inteiro
  // altura do triangulo
  altura : inteiro
  // area
  area : inteiro
Inicio
  // Seção de Comandos
  //lendo a base 
  escreval("Digite a base triângulo: ")
  leia(base)
  //lendo a altura 
  escreval("Digite a altura do triângulo: ")
  leia(altura)

  // media aritimetica dos dois numeros
  area <- (base * altura)/2

  escreval("A área do triângulo é ", area)








fimalgoritmo